package com.joel.car_compose.model

import com.joel.car_compose.R

object DataStore {

    val carList = listOf(
        Car(
            id = 1,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 2,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 3,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 4,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 5,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 6,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 7,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 8,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 9,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 10,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        ),
        Car(
            id = 11,
            overView = "",
            horsPower = 1500,
            price = 2300000.0,
            brand = "BMW",
            model = "320i",
            fuelType = "Hybrid",
            imageURL =  R.drawable.img_bmw,
            year = 2017,
        )
    )
}